#!/usr/bin/env python3
"""
Generate an instrumented copy of the vendored SGLang RadixCache for op-counting.

Reads:  third_party/sglang_radix_cache/radix_cache.py  (byte-identical to v0.1.17)
Writes: third_party/sglang_radix_cache/radix_cache_instrumented.py

The generated file adds:
  - _comparison_count: incremented per token comparison in _key_match
  - _node_visit_count: incremented per node visited in _match_prefix_helper
  - get_comparison_count() / reset_comparison_count()
  - get_node_visit_count() / reset_node_visit_count()
  - reset_all_counters()

The tree algorithm is OTHERWISE IDENTICAL to the vendored file. All timing
runs use the byte-identical vendored file; this instrumented copy is used
ONLY for the op-count guard passes in EXP-017.

Usage (from paper-repo root):
    python tools/make_instrumented_radix.py

The script verifies the input SHA-256 before patching and prints the output
SHA-256 for reproducibility.
"""
import hashlib
import os
import sys

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
VENDOR_DIR = os.path.join(REPO_ROOT, "third_party", "sglang_radix_cache")
INPUT_PATH = os.path.join(VENDOR_DIR, "radix_cache.py")
OUTPUT_PATH = os.path.join(VENDOR_DIR, "radix_cache_instrumented.py")

EXPECTED_SHA256 = "42749c7cf0f3cbf42066dd273360730c8fe10e2a21983a49f102a500702ca71c"

# --- The header prepended to the generated file ---
GENERATED_HEADER = '''\
# =========================================================================
# AUTO-GENERATED — DO NOT EDIT
# =========================================================================
# This file was generated by tools/make_instrumented_radix.py from the
# byte-identical vendored radix_cache.py (SGLang v0.1.17, SHA-256
# 42749c7c...702ca71c). It adds comparison and node-visit counters for
# EXP-017 op-count guard passes ONLY.
#
# *** NEVER USE THIS FILE FOR TIMING. ***
# All timed runs must use the unmodified radix_cache.py.
# =========================================================================

'''

# --- Counter module inserted after "import torch" ---
COUNTER_BLOCK = '''
# --- EXP-017 instrumentation counters (auto-generated) ---
_comparison_count = 0
_node_visit_count = 0


def get_comparison_count():
    """Return the cumulative token-comparison count since last reset."""
    return _comparison_count


def reset_comparison_count():
    """Reset the token-comparison counter to 0."""
    global _comparison_count
    _comparison_count = 0


def get_node_visit_count():
    """Return the cumulative node-visit count since last reset."""
    return _node_visit_count


def reset_node_visit_count():
    """Reset the node-visit counter to 0."""
    global _node_visit_count
    _node_visit_count = 0


def reset_all_counters():
    """Reset all instrumentation counters to 0."""
    reset_comparison_count()
    reset_node_visit_count()
# --- end instrumentation counters ---

'''

# --- Patches (old_text -> new_text) applied in order ---
PATCHES = [
    # Patch 1: insert counter block after "import torch\n"
    (
        "import torch\n",
        "import torch\n" + COUNTER_BLOCK,
    ),
    # Patch 2: instrument _key_match with comparison counter
    (
        "def _key_match(key0, key1):\n"
        "    i = 0\n"
        "    for k0, k1 in zip(key0, key1):\n"
        "        if k0 != k1:\n"
        "            break\n"
        "        i += 1\n"
        "    return i\n",

        "def _key_match(key0, key1):\n"
        "    global _comparison_count\n"
        "    i = 0\n"
        "    for k0, k1 in zip(key0, key1):\n"
        "        _comparison_count += 1\n"
        "        if k0 != k1:\n"
        "            break\n"
        "        i += 1\n"
        "    return i\n",
    ),
    # Patch 3: instrument _match_prefix_helper with node-visit counter
    (
        "    def _match_prefix_helper(self, node, key, value, last_node):\n"
        "        node.last_access_time = time.time()\n",

        "    def _match_prefix_helper(self, node, key, value, last_node):\n"
        "        global _node_visit_count\n"
        "        _node_visit_count += 1\n"
        "        node.last_access_time = time.time()\n",
    ),
]


def main():
    # Read and verify input
    with open(INPUT_PATH, "r", encoding="utf-8") as f:
        source = f.read()

    sha = hashlib.sha256(source.encode("utf-8")).hexdigest()
    if sha != EXPECTED_SHA256:
        print(f"ERROR: input SHA-256 mismatch", file=sys.stderr)
        print(f"  expected: {EXPECTED_SHA256}", file=sys.stderr)
        print(f"  got:      {sha}", file=sys.stderr)
        sys.exit(1)
    print(f"Input verified: {INPUT_PATH}")
    print(f"  SHA-256: {sha}")

    # Apply patches
    patched = source
    for i, (old, new) in enumerate(PATCHES, 1):
        count = patched.count(old)
        if count != 1:
            print(f"ERROR: patch {i} anchor appears {count} times (expected 1)",
                  file=sys.stderr)
            sys.exit(1)
        patched = patched.replace(old, new, 1)
        print(f"  Patch {i}/{len(PATCHES)} applied")

    # Prepend header
    output = GENERATED_HEADER + patched

    # Write output
    with open(OUTPUT_PATH, "w", encoding="utf-8", newline="\n") as f:
        f.write(output)

    out_sha = hashlib.sha256(output.encode("utf-8")).hexdigest()
    print(f"Output written: {OUTPUT_PATH}")
    print(f"  SHA-256: {out_sha}")
    print(f"  Lines:   {output.count(chr(10))}")
    print("Done.")


if __name__ == "__main__":
    main()
